program: e_run_optuna.py
method: bayes  # Bayesian optimization using W&B
metric:
  goal: minimize
  name: test_loss  #  Now logs test loss

parameters:
  learning_rate:
    min: 0.005
    max: 0.2
    distribution: uniform  #  Searchable parameter

  weight_decay:
    min: 0.0001
    max: 0.01
    distribution: uniform  #  Searchable parameter

  start_fraction:
    min: 0.1
    max: 0.5
    distribution: uniform  # Searchable parameter

  inc:
    min: 0.05
    max: 0.4
    distribution: uniform  # Searchable parameter

  step_length:
    min: 0.2
    max: 5
    distribution: uniform  #  Searchable integer parameter

  starting_portion:
    min: 0.1
    max: 0.3
    distribution: uniform  #  Searchable parameter
